apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: calico-ipsec-node
  namespace: kube-system
  labels:
    k8s-app: calico-ipsec-node
spec:
  selector:
    matchLabels:
      k8s-app: calico-ipsec-node
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: calico-ipsec-node
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      - operator: Exists
        key: CriticalAddonsOnly
      hostNetwork: true
      dnsPolicy: Default  # Don't use cluster DNS.
      automountServiceAccountToken: false
      volumes:
      - name: ipsec-conf
        emptyDir: {}
      - name: ipsec-secrets
        secret:
          secretName: calico-ipsec
      containers:
      - name: ipsec
        image: adohkan/calico-ipsec
        volumeMounts:
        - name: ipsec-conf
          mountPath: /etc/calico-ipsec-conf
        - name: ipsec-secrets
          mountPath: /etc/calico-ipsec-secrets
          readOnly: true
        command:
        - /sbin/tini
        args:
        - "--"
        - "ipsec"
        - "start"
        - "--nofork"
        - "--auto-update"
        - "15"
        ports:
        - containerPort: 500
          name: isakmp
          protocol: UDP
        resources:
          requests:
            cpu: 150m
            memory: 20Mi
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
      - name: build-ipsec-conf
        image: adohkan/calico-ipsec
        volumeMounts:
        - name: ipsec-conf
          mountPath: /etc/calico-ipsec-conf
        env:
        - name: IPSEC_CONF_DIR
          value: "/etc/calico-ipsec-conf"
        #- name: IPSEC_AUTHBY
        #  value: ""
        #- name: IPSEC_PROTOPORT
        # uncomment for VXLAN
        #  value: "[udp/8472]"
        command:
        - /sbin/tini
        args:
        - "--"
        - "/bin/sh"
        - "-eu"
        - "-c"
        - "cd $IPSEC_CONF_DIR && while :; do build-ipsec-conf.sh > ipsec.conf.tmp && mv ipsec.conf.tmp ipsec.conf; sleep 15; done"
        resources:
          requests:
            cpu: 150m
            memory: 20Mi
